name: Snyk test
on: push
jobs:
security:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@master
- uses: snyk/actions/setup@master
- uses: actions/setup-go@v1
- name: Snyk test
run: snyk test --all-projects
env:
SNYK_TOKEN:SYNK_SECRET
#SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
